testproject/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from timetracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='timetracker/login.html')),
    path('logout/', auth_views.LogoutView.as_view(template_name='timetracker/logout.html')),
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.TimeEntryCreateView.as_view(), name='add'),
    path('remove/<int:time_entry_id>', views.remove_time_entry, name='remove'),
    path('edit/<int:time_entry_id>', views.TimeEntryUpdateView.as_view(), name='edit'),
]

timetracker/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Project(models.Model):
    name = models.CharField(max_length=200, default="noname")

    def __str__(self):
        return self.name


class TimeEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateField('work on date', default=timezone.now)
    duration = models.IntegerField('work duration in seconds', default=0)
    comment = models.TextField('optionnal comment', default="")

    def __str__(self):
        return "time entry [user=" + str(
            self.user.id) + "] [date=" + self.date.__str__() + "] [duration=" + str(self.duration) + "]"

timetracker/forms.py
from django import forms
from django.contrib.auth.models import User

from timetracker.models import Project, TimeEntry


class TimeEntryForm(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    project = forms.ModelChoiceField(queryset=Project.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control'}))
    duration = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)

    def save_timeentry(self, timeentry_id=None):
        if timeentry_id:
            timeentry = TimeEntry.objects.get(pk=timeentry_id)
        else:
            timeentry = TimeEntry()
        timeentry.project = self.cleaned_data['project']
        timeentry.user = self.cleaned_data['user']
        hours, minutes = self.cleaned_data['duration'].split(':')
        timeentry.duration = int(hours) * 3600 + int(minutes) * 60
        timeentry.date = self.cleaned_data['date']
        timeentry.comment = self.cleaned_data['comment']
        timeentry.save()
        pass

timetracker/views.py
import math

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic import CreateView, FormView

from timetracker.forms import TimeEntryForm
from timetracker.models import TimeEntry, Project


class IndexView(generic.ListView):
    template_name = 'timetracker/index.html'
    context_object_name = 'timeentrys'

    def get_queryset(self):
        user = None
        if self.request.user.is_authenticated:
            user = self.request.user

        time_entrys = TimeEntry.objects.filter(user=user)

        project_id = self.request.GET.get('project_id')
        if project_id and len(project_id) > 0:
            project_id = int(project_id)
            time_entrys = time_entrys.filter(project_id=project_id)

        date_min = self.request.GET.get('date_min')
        if date_min and len(date_min) > 0:
            # date_min = (date_min)
            time_entrys = time_entrys.filter(date__gte=date_min)

        date_max = self.request.GET.get('date_max')
        if date_max and len(date_max) > 0:
            # date_max = (date_max)
            time_entrys = time_entrys.filter(date__lte=date_max)

        total = 0
        for time_entry in time_entrys:
            total += time_entry.duration

        self.extra_context = {"total": total,
                              "project_id": project_id,
                              "date_min": date_min,
                              "date_max": date_max,
                              "projects": Project.objects.all()}
        return time_entrys.order_by('-id')


class TimeEntryCreateView(FormView):
    template_name = 'timetracker/timeentry_form.html'
    form_class = TimeEntryForm
    success_url = '/'

    def get_initial(self):
        initial = super(TimeEntryCreateView, self).get_initial()
        if self.request.user.is_authenticated:
            initial.update({'user': self.request.user})
            user_entries = TimeEntry.objects.filter(user=self.request.user).order_by('-id')
            if len(user_entries) > 0:
                initial.update({'project': user_entries[0].project})
        initial.update({"date": timezone.now})
        return initial

    def form_valid(self, form):
        form.save_timeentry()
        return super().form_valid(form)


class TimeEntryUpdateView(FormView):
    template_name = 'timetracker/timeentry_form.html'
    form_class = TimeEntryForm
    success_url = '/'

    @property
    def time_entry_id(self):
        return self.kwargs['time_entry_id']

    def get_initial(self):
        time_entry = get_object_or_404(TimeEntry, pk=self.time_entry_id)
        initial = super(TimeEntryUpdateView, self).get_initial()
        hour = math.floor(time_entry.duration / 3600)
        minutes = math.floor((time_entry.duration - (hour * 3600)) / 60)
        initial.update({
            "project": time_entry.project,
            "user": time_entry.user,
            "date": time_entry.date,
            "duration": str(hour) + ':' + str(minutes),
            "comment": time_entry.comment,
        })
        return initial

    def form_valid(self, form):
        form.save_timeentry(self.time_entry_id)
        return super().form_valid(form)


def remove_time_entry(request, time_entry_id):
    # TODO : check user permissions
    time_entry = get_object_or_404(TimeEntry, pk=time_entry_id)
    time_entry.delete()
    return HttpResponseRedirect(reverse('index'))

timetracker/templates/timetracker/base.html
<!DOCTYPE html>
<html lang=en>
<head>
    {% load static %}
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <link rel=icon href=/favicon.ico>
    <title>Time tracker</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet"
          href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
          integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <style type="text/css">
        :root {
            --jumbotron-padding-y: 3rem;
        }

        .jumbotron {
            padding-top: var(--jumbotron-padding-y);
            padding-bottom: var(--jumbotron-padding-y);
            margin-bottom: 0;
            background-color: #fff;
        }

        @media (min-width: 768px) {
            .jumbotron {
                padding-top: calc(var(--jumbotron-padding-y) * 2);
                padding-bottom: calc(var(--jumbotron-padding-y) * 2);
            }
        }

        .jumbotron p:last-child {
            margin-bottom: 0;
        }

        .jumbotron-heading {
            font-weight: 300;
        }

        .jumbotron .container {
            max-width: 40rem;
        }

        footer {
            padding-top: 3rem;
            padding-bottom: 3rem;
        }

        footer p {
            margin-bottom: .25rem;
        }

        .box-shadow {
            box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
        }
    </style>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark box-shadow">
        <a class="navbar-brand" href="/">Time tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">My times</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/add/">Add a new time</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout/">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main role="main" id="app">
    {% block main %}
    {% endblock %}
</main>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
{#    <script src="../../../../assets/js/vendor/popper.min.js"></script>#}
{#    <script src="../../../../assets/js/vendor/holder.min.js"></script>#}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
        integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
        integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
        crossorigin="anonymous"></script>
{% load static %}
<script src="{% static "js/moment-with-locales.min.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vuejs-datepicker"></script>
<script src="{% static "js/script.js" %}"></script>
{% block javascripts %}
{% endblock %}
</body>
</html>

timetracker/templates/timetracker/index.html
{% extends 'timetracker/base.html' %}
{% block main %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Your time entries</h1>
        </div>
    </section>
    <div class="py-5 bg-light">
        <div class="container">
            <form method="get" action="/" class="form-inline">
                <button type="submit" class="btn btn-primary mt-2 mr-4 ml-0">Filter by</button>
                <div class="form-group mr-3">
                    <label for="select-project" class="mr-3">Projects</label>
                    <select class="form-control my-1 mr-sm-2" id="select-project" name="project_id" style="min-width: 150px">
                        <option value="">none</option>
                        {% for project in projects %}
                            <option value="{{ project.id }}"
                                    {% if project.id == project_id %}selected{% endif %}>{{ project.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mr-4">
                    <label for="select-project" class="mr-3">Date min</label>
                    <vuejs-datepicker value="'{{ date_min }}'"
                                      name="date_min"
                                      bootstrap-styling
                                      format="yyyy-MM-dd"
                                      clear-button
                    ></vuejs-datepicker>
                </div>
                <div class="form-group mr-4">
                    <label for="select-project" class="mr-3">Date max</label>
                    <vuejs-datepicker value="'{{ date_max }}'"
                                      name="date_max"
                                      bootstrap-styling
                                      format="yyyy-MM-dd"
                                      clear-button
                    ></vuejs-datepicker>
                </div>
            </form>
            <table class="table">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Project</th>
                    <th>Time</th>
                    <th>Comment</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for timeentry in timeentrys %}
                    <tr>
                        <td>{{ timeentry.date }}</td>
                        <td>{{ timeentry.project }}</td>
                        <td>
                            <app-duration duration="{{ timeentry.duration }}"></app-duration>
                        </td>
                        <td>{{ timeentry.comment }}</td>
                        <td>
                            <a href="/edit/{{ timeentry.id }}">Edit</a> |
                            <a href="/remove/{{ timeentry.id }}"
                               onclick="if (!confirm('confirm remove ?')) return false">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="7">
                        Total time :
                        <app-duration duration="{{ total }}"></app-duration>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

timetracker/templates/timetracker/login.html
{% extends 'timetracker/base.html' %}
{% block main %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Identify yourself</h1>
        </div>
    </section>
    <div class="py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form }}
                                <button type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

timetracker/templates/timetracker/logout.html
{% extends 'timetracker/base.html' %}
{% block main %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Log out</h1>
        </div>
    </section>
    <div class="py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            Déconnecté ?
                            <a href="/">Revenir à l'accueil</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

timetracker/templates/timetracker/timeentry_form.html
{% extends 'timetracker/base.html' %}
{% block main %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">input your time</h1>
        </div>
    </section>
    <div class="py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.project.errors }}
                                    {{ form.project.label_tag }}
                                    {{ form.project }}
                                </div>
                                <div class="form-group">
                                    {{ form.user.errors }}
                                    {{ form.user.label_tag }}
                                    {{ form.user }}
                                </div>
                                <div class="form-group">
                                    {{ form.duration.errors }}
                                    {{ form.duration.label_tag }}
                                    <input type="text" name="duration" required="required" id="id_duration" class="form-control"
                                           onblur="formatDurationInput(this)" value="{{ form.duration.value }}">
                                </div>

                                <div class="form-group">
                                    {{ form.date.errors }}
                                    {{ form.date.label_tag }}
{#                                    {{ form.date }}#}
                                <vuejs-datepicker value="'{{form.date.value|date:'Y-m-d'}}'"
                                                  name="date" bootstrap-styling
                                                  format="yyyy-MM-dd"
                                                  ></vuejs-datepicker>
                                </div>
                                <div class="form-group">
                                    {{ form.comment.errors }}
                                    {{ form.comment.label_tag }}
                                    {{ form.comment }}
                                </div>
                                <button type="submit" class="btn btn-primary">Save time entry</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {% verbatim %}
    <script type="text/javascript">
        function formatDurationInput(input) {
            console.log(input.value, typeof input.value);
            if (input.value.indexOf(':') !== -1) return;

            let value = input.value;
            let minutes = '';
            let hours = '';
            if (value > 10) {
                // minutes
                minutes = value % 60;
                hours = Math.floor(value / 60);

            } else {
                // hours
                minutes = 60 * (value % 1);
                hours = Math.floor(value);
            }
            hours = '' + hours;
            minutes = '' + minutes;
            hours = hours.length < 2 ? '0' + hours : hours;
            minutes = minutes.length < 2 ? '0' + minutes : minutes;
            input.value = hours + ':' + minutes

        }
    </script>
    {% endverbatim %}
{% endblock %}